### ISSUE TITLE
[Feature Request] Add Action - Put specific listener client into preview or program mode

### ISSUE THREAD

**Issue by BenJamesAndo** [bitfocus/companion-module-techministry-tallyarbiter#3]
Hello. Would it be possible to add a feature to put a listener client into preview or program mode? I use the flashing action when we go off air to communicate to the camera operator that we're done. But being able to use this module to put specific clients into preview or program mode would be nice. It would open up the door to a lot of possibilities.

Currently I use OSC in Companion to control the tally lights but doing it directly through tallyarbiter module would be great.

**Comment by josephdadams** [comment]
Could you add an OSC source type in tally arbiter and put your camera in preview through OSC?

**Comment by BenJamesAndo** [comment]
Yes, but what I was getting at is to have the Tally Arbiter module itself be able to put a listener into preview or program mode. This would just make it simpler and easier. But it would be a luxury feature for sure.

**Comment by josephdadams** [comment]
It would have to be the way I mentioned, because clients are intended to stay in sync with Tally Arbiter.
