### ISSUE TITLE
TallyArbiter-set-devices-in-companion

### ISSUE THREAD

**Issue by glop24** [bitfocus/companion-module-techministry-tallyarbiter#4]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I wanted to know if it would be possible to configure the devices from companion, 
in order to make tally crosspoints faster on the same key. 
Or do you know another way to make TSL crosspoint ?

**Comment by Julusian** [comment]
Is this asking for a new module to talk to tallyarbiter or something more complex?

**Comment by glop24** [comment]
Sorry my question was not very clear. 
Is it possible to do a new action in the TallyArbiter module, that would correspond to the parameter "Devices/Edit Source/Source Address" and to be able to select a source address already in preset. 
The idea is to be able to make crosspoint callbacks between a device and a source address.

**Comment by josephdadams** [comment]
I am the author of tallyarbiter and I don't understand what you are asking for
